package edu.progAvUD.taller1.vista;

import edu.progAvUD.taller1.control.ControlGrafico;
import java.awt.Font;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 * Representa la ventana principal de la aplicación gráfica. Controla y gestiona
 * el cambio entre los diferentes paneles del sistema, mostrando la interfaz
 * correspondiente según la opción seleccionada.
 *
 * También ofrece métodos para mostrar mensajes de éxito o error al usuario.
 *
 * @author Andres Felipe
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Controlador gráfico encargado de manejar la lógica de la interfaz.
     */
    private ControlGrafico controlGrafico;

    /**
     * Panel inicial de la aplicación.
     */
    public PanelInicial panelInicial;

    /**
     * Panel que muestra los menús tipo Bucket.
     */
    public PanelBuckets panelBuckets;

    /**
     * Panel que muestra los menús tipo Combo.
     */
    public PanelCombos panelCombos;

    /**
     * Panel que muestra los productos que no son parte de combos ni buckets.
     */
    public PanelOtrosProductos panelOtrosProductos;

    /**
     * Panel encargado del proceso de pago.
     */
    public PanelPagar panelPagar;

    /**
     * Panel que muestra los productos para compartir.
     */
    public PanelParaCompartir panelParaCompartir;

    /**
     * Constructor que inicializa la ventana principal y sus paneles.
     *
     * @param controlGrafico Controlador gráfico encargado de la lógica de UI.
     */
    public VentanaPrincipal(ControlGrafico controlGrafico) {
        this.controlGrafico = controlGrafico;
        initComponents();
        setVisible(true);
        this.panelInicial = new PanelInicial();
        this.panelBuckets = new PanelBuckets();
        this.panelCombos = new PanelCombos();
        this.panelOtrosProductos = new PanelOtrosProductos();
        this.panelPagar = new PanelPagar();
        this.panelParaCompartir = new PanelParaCompartir();
        jMenuBar1.setVisible(false);
    }

    /**
     * Muestra en la ventana principal el panel especificado.
     *
     * @param panel Panel a mostrar en la ventana.
     */
    public void mostrarPanel(JPanel panel) {
        setContentPane(panel);
        pack(); // Ajusta el tamaño de la ventana según el contenido
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        revalidate();
        repaint();
    }

    /**
     * Muestra un cuadro de diálogo con un mensaje de éxito.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Muestra un cuadro de diálogo con un mensaje de error.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public int preguntarMedioDePago() {
        String[] opciones = {"Tarjeta", "Efectivo", "Puntos"};
        // Mostrar el JOptionPane
        int seleccion = JOptionPane.showOptionDialog(
                null,
                "¿Con que medio de pago deceas relizar el pedido?",
                "Seleccione una opción",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );
        return seleccion;
    }

    public void realizandoPago() {
        JDialog dialogo = new JDialog();
        dialogo.setUndecorated(true); // Sin barra de título ni botones
        dialogo.setAlwaysOnTop(true); // Que esté siempre encima
        dialogo.setModal(true); // Bloquea otros eventos

        JLabel label = new JLabel("Se está haciendo el pago...", SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.PLAIN, 16));
        label.setBorder(BorderFactory.createEmptyBorder(20, 40, 20, 40));

        dialogo.getContentPane().add(label);
        dialogo.pack();
        dialogo.setLocationRelativeTo(null);

        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            public void run() {
                dialogo.dispose();
            }
        }, 10000); 

        dialogo.setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCrearBucket = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCrearCombo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemParaCompartir = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemMasProductos = new javax.swing.JMenuItem();
        jMenuPagar = new javax.swing.JMenu();
        jMenuItemPagar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenu1.setText("Buckets");

        jMenuItemCrearBucket.setText("Crea tu bucket");
        jMenu1.add(jMenuItemCrearBucket);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Combos");

        jMenuItemCrearCombo.setText("Crea tu Combo");
        jMenu2.add(jMenuItemCrearCombo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Para Compartir");

        jMenuItemParaCompartir.setText("Combos Para Compartir");
        jMenu3.add(jMenuItemParaCompartir);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Otros Productos");

        jMenuItemMasProductos.setText("Mas Productos");
        jMenu5.add(jMenuItemMasProductos);

        jMenuBar1.add(jMenu5);

        jMenuPagar.setText("Pagar");

        jMenuItemPagar.setText("Ir a pagar");
        jMenuPagar.add(jMenuItemPagar);

        jMenuBar1.add(jMenuPagar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemCrearBucket;
    public javax.swing.JMenuItem jMenuItemCrearCombo;
    public javax.swing.JMenuItem jMenuItemMasProductos;
    public javax.swing.JMenuItem jMenuItemPagar;
    public javax.swing.JMenuItem jMenuItemParaCompartir;
    public javax.swing.JMenu jMenuPagar;
    // End of variables declaration//GEN-END:variables
}
